apiVersion: v1
kind: Namespace
metadata:
  name: bereziuk-yevhenii 
  labels:
    env: stage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bereziuk-app-deployment
  namespace: bereziuk-yevhenii 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bereziuk-app
  template:
    metadata:
      labels:
        app: bereziuk-app
    spec:
      serviceAccountName: secret-bereziuk-sa
      volumes:
        - name:  secret 
          secret: 
            secretName: mysecret
        - name: config
          configMap: 
            name: env-vars
            items:
              - key: env
                path: "env"
      restartPolicy: Always
      containers:
      - name: bereziuk-app
        image: httpd:2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: apache-port
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 5
          httpGet:
            port: 80
            path: / 
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 6
          periodSeconds: 10
          httpGet: 
            port: 80
            path: /
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
          - name: ENVIRONMENT1
            valueFrom:
              configMapKeyRef:
                name: env-vars
                key: env
          - name: MASSTER_PASS
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
        volumeMounts:
          - mountPath:  "/config"
            name: config 
            readOnly: true
          - mountPath: "/secret"
            name: secret 
            readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: bereziuk-yevhenii
  labels:
    app: bereziuk-app
spec:
  selector:
    app: bereziuk-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: apache-port
  type: LoadBalancer