apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: study
  name: nginx1
  labels:
    app: server1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server1
  template:
    metadata:
      labels:
        app: server1
    spec:
      serviceAccountName: secret-sa
      volumes:
        - name:  secret 
          secret: 
            secretName: mysecret
        - name: config
          configMap: 
            name: env-vars
            items:
              - key: env
                path: "env"
      restartPolicy: Always
      containers:
      - name: nginx1
        image: library/nginx:1.18-alpine
        imagePullPolicy: IfNotPresent
        ports: 
          - containerPort: 80
            name: nginx-port
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 5
          httpGet:
            port: 80
            path: / 
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 6
          periodSeconds: 10
          httpGet: 
            port: 80
            path: /
        resources:
          requests: 
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "250Mi"
            cpu: "250m"
        env:
          - name: ENVIRONMENT1
            valueFrom:
              configMapKeyRef:
                name: env-vars
                key: env
          - name: MASSTER_PASS
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
        volumeMounts:
          - mountPath:  "/config"
            name: config 
            readOnly: true
          - mountPath: "/secret"
            name: secret 
            readOnly: true
            

