apiVersion: v1
kind: Service
metadata:
  namespace: study
  name: nginx1
spec:
  type: LoadBalancer
  selector:
    app: server1
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
