apiVersion: v1
kind: Pod
metadata:
  namespace: study
  name: multiple_1
spec:
  containers:
    - name: nginx
      image: library/nginx:1.14.2
      ports:
        - containerPort: 80
    - name: busybox
      image: library/busybox:1.28
      command: ['sh', '-c', 'echo "Hello busybox" && sleep 60']
  restartPolicy: OnFailure
