apiVersion: v1
kind: Pod
metadata:
  namespace: study
  name: init_containers_1
spec:
  initContainers:
    - name: busybox
      image: library/busybox:1.28
      command: ['sh', '-c', 'echo "Hello busybox" && sleep 10']
    - name: busybox2
      image: library/busybox:1.28
      command: ['sh', '-c', 'echo "Hello busybox" && sleep 20']    
  containers:
    - name: nginx
      image: library/nginx:1.14.2
      ports:
        - containerPort: 80
  restartPolicy: OnFailure
