apiVersion: v1
kind: Pod
metadata:
  namespace: study
  name: variables_1
spec:
  containers:
    - name: nginx
      image: library/nginx:latest
      imagePullPolicy: Always
      env:
        - name: ENVIRONMENT
          value: "PROD"
      ports:
        - containerPort: 80
          
