apiVersion: v1
kind: Pod
metadata:
  namespace: study
  name: volume
spec:
  containers:
    - name: nginx
      image: library/nginx:1.14.2
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /data/nginx
          name: nginx-storage

  volumes:
    - name: nginx-storage
      emptyDir: {}
