apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: study
  name: pvc-test
spec:
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi