apiVersion: apps/v1
kind: ReplicaSet 
metadata:
   namespace: study
   name: web-server1
   labels:
     app: server 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server 
  template:
    metadata:
      labels:
        app: server 
    spec:
      containers:
        - name:  nginx
          imagePullPolicy: IfNotPresent
          image: library/nginx:1.14.2
          ports:
            - containerPort: 80
              name: server 
      